// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp1A9_9EtBEtUFPq_4KUObsZy7ky0G_9w',
    appId: '1:468953482168:web:04ec892d772a242531854d',
    messagingSenderId: '468953482168',
    projectId: 'pulso-ecg',
    authDomain: 'pulso-ecg.firebaseapp.com',
    storageBucket: 'pulso-ecg.firebasestorage.app',
    measurementId: 'G-LZWMZ68M74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMPJEV83C3rL5tsu2uh6gsxIoZG_Hzy-Y',
    appId: '1:468953482168:android:1317fea94002e7a531854d',
    messagingSenderId: '468953482168',
    projectId: 'pulso-ecg',
    storageBucket: 'pulso-ecg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAreDldZeBAP9bkbfUu3GGTWQobV0-h324',
    appId: '1:468953482168:ios:324144e09ce52bf131854d',
    messagingSenderId: '468953482168',
    projectId: 'pulso-ecg',
    storageBucket: 'pulso-ecg.firebasestorage.app',
    iosBundleId: 'com.example.pulsoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAreDldZeBAP9bkbfUu3GGTWQobV0-h324',
    appId: '1:468953482168:ios:324144e09ce52bf131854d',
    messagingSenderId: '468953482168',
    projectId: 'pulso-ecg',
    storageBucket: 'pulso-ecg.firebasestorage.app',
    iosBundleId: 'com.example.pulsoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp1A9_9EtBEtUFPq_4KUObsZy7ky0G_9w',
    appId: '1:468953482168:web:12eda35fd36b8da531854d',
    messagingSenderId: '468953482168',
    projectId: 'pulso-ecg',
    authDomain: 'pulso-ecg.firebaseapp.com',
    storageBucket: 'pulso-ecg.firebasestorage.app',
    measurementId: 'G-9R6CGSPWB8',
  );
}
